apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards
  namespace: eazybank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cards
  template:
    metadata:
      labels:
        app: cards
    spec:
      containers:
        - name: cards
          image: eazybank/cards:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: CONFIG_SERVER_HOST
              value: configserver
            - name: EUREKA_SERVER_HOST
              value: eurekaserver