apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eazybank-gateway
  namespace: eazybank
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gatewayserver
                port:
                  number: 8072
