apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  namespace: eazybank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
        - name: configserver
          image: eazybank/configserver:1.0
          ports:
            - containerPort: 8071
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8071
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8071
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "native"